[project]
name = "aibookvideo"
version = "0.1.0"
description = "AI书籍视频生成工具"
readme = "README.md"
requires-python = ">=3.9,<3.12"
dependencies = [
    "flask>=3.1.1",
    "pymysql>=1.1.1",
    "dotenv==0.9.9",
    "moviepy>=2.2.1",
    "cors>=1.0.1",
    "flask-cors>=6.0.1",
    "TTS>=0.22.0"
]
